[package]
name = "rsil-rpc-sil-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Rsil RPC 'sil' namespace API"

[lints]
workspace = true

[dependencies]
# rsil
revm = { workspace = true, features = ["optional_block_gas_limit", "optional_eip3607", "optional_no_base_fee", "optional_fee_charge", "memory_limit"] }
rsil-chain-state.workspace = true
revm-inspectors.workspace = true
rsil-primitives-traits = { workspace = true, features = ["rpc-compat"] }
rsil-errors.workspace = true
rsil-savm.workspace = true
rsil-storage-api.workspace = true
rsil-revm.workspace = true
rsil-rpc-convert.workspace = true
rsil-tasks = { workspace = true, features = ["rayon"] }
rsil-transaction-pool.workspace = true
rsil-chainspec.workspace = true
rsil-rpc-sil-types.workspace = true
rsil-rpc-server-types.workspace = true
rsil-network-api.workspace = true
rsil-node-api.workspace = true
rsil-trie-common = { workspace = true, features = ["sip1186"] }
rsil-prune-types.workspace = true

# sila
alloy-savm = { workspace = true, features = ["overrides", "call-util"] }
alloy-rlp.workspace = true
alloy-serde.workspace = true
alloy-sips.workspace = true
alloy-sip7928 = { workspace = true, features = ["rlp"] }
alloy-dyn-abi = { workspace = true, features = ["sip712"] }
alloy-json-rpc.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-sil.workspace = true
alloy-rpc-types-mev.workspace = true
alloy-consensus.workspace = true

# rpc
jsonrpsee = { workspace = true, features = ["server", "macros"] }
jsonrpsee-types.workspace = true

# async
async-trait.workspace = true
futures.workspace = true
parking_lot.workspace = true
tokio.workspace = true

# misc
auto_impl.workspace = true
dyn-clone.workspace = true
serde_json.workspace = true
tracing.workspace = true

[features]
js-tracer = ["revm-inspectors/js-tracer", "rsil-rpc-sil-types/js-tracer"]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
