[package]
name = "example-custom-beacon-withdrawals"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
rsil-sila = { workspace = true, features = ["node", "node-api", "savm", "cli"] }

alloy-savm.workspace = true
alloy-sol-types.workspace = true
alloy-sips.workspace = true

eyre.workspace = true
