[package]
name = "rsil-rpc-convert"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Compatibility layer for rsil-primitives and sila RPC types"

[lints]
workspace = true

[dependencies]
# rsil
rsil-primitives-traits.workspace = true
rsil-savm.workspace = true
rsil-rpc-traits.workspace = true

# sila
alloy-primitives.workspace = true
alloy-rpc-types-sil = { workspace = true, features = ["serde"] }
alloy-consensus.workspace = true
alloy-network.workspace = true
alloy-json-rpc.workspace = true
alloy-savm = { workspace = true, features = ["rpc"] }

# io
jsonrpsee-types.workspace = true

# error
thiserror.workspace = true

auto_impl.workspace = true
dyn-clone.workspace = true

[dev-dependencies]
serde_json.workspace = true

[features]
default = []
