[package]
name = "rsil-net-banlist"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Banlist for peers and IPs"

[lints]
workspace = true

[dependencies]
# sila
alloy-primitives.workspace = true

# networking
ipnet.workspace = true
