[package]
name = "example-precompile-cache"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
rsil-sila = { workspace = true, features = ["test-utils", "savm", "node-api", "node"] }
rsil-tracing.workspace = true
alloy-savm.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true

eyre.workspace = true
parking_lot.workspace = true
schnellru.workspace = true
tokio.workspace = true
