[package]
name = "rsil-payload-util"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "rsil payload utilities"

[lints]
workspace = true

[dependencies]
# rsil
rsil-transaction-pool.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-consensus.workspace = true
