[package]
name = "ef-tests"
version.workspace = true
description = "EF testing support for rsil."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
ef-tests = []
asm-keccak = ["alloy-primitives/asm-keccak", "revm/asm-keccak"]

[dependencies]
rsil-chainspec.workspace = true
rsil-sila-primitives.workspace = true
rsil-primitives-traits = { workspace = true, features = ["rayon"] }
rsil-consensus.workspace = true
rsil-db = { workspace = true, features = ["mdbx", "test-utils", "disable-lock"] }
rsil-db-api.workspace = true
rsil-db-common.workspace = true
rsil-provider = { workspace = true, features = ["test-utils"] }
rsil-savm.workspace = true
rsil-savm-sila.workspace = true
rsil-sila-consensus.workspace = true
rsil-revm.workspace = true
rsil-tracing.workspace = true
rsil-trie.workspace = true
rsil-trie-db.workspace = true
revm = { workspace = true, features = ["secp256k1", "blst", "c-kzg", "memory_limit", "p256-aws-lc-rs"] }

alloy-rlp.workspace = true
alloy-primitives.workspace = true
alloy-sips.workspace = true
alloy-consensus.workspace = true
alloy-genesis.workspace = true

walkdir.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
rayon.workspace = true
