[package]
name = "example-custom-payload-builder"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
rsil-basic-payload-builder.workspace = true
rsil-payload-builder.workspace = true
rsil-sila = { workspace = true, features = ["node", "pool", "cli"] }
rsil-sila-payload-builder.workspace = true

alloy-sips.workspace = true

tracing.workspace = true
futures-util.workspace = true
eyre.workspace = true
